<?php

$line_1 = [
    ['name' => '莘庄', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '外环路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '莲花路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '锦江乐园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海南站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '漕宝路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海体育馆', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '徐家汇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '衡山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '常熟路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '陕西南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '黄陂南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '人民广场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '新闸路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '汉中路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海火车站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中山北路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '延长路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海马戏城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '汶水路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '彭浦新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '共康路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '通河新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '呼兰路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '共富新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宝安公路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '友谊西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '富锦路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_2 = [
    ['name' => '徐泾东', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥火车站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥2号航站楼', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '淞虹路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '北新泾', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '威宁路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '娄山关路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中山公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江苏路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '静安寺', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '南京西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '人民广场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '南京东路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '陆家嘴', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东昌路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '世纪大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海科技馆', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '世纪公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙阳路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '张江高科', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金科路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '广兰路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '唐镇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '创新中路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '华夏东路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '川沙', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '凌空路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '远东大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '海天三路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '浦东国际机场', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_3 = [
    ['name' => '上海南站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '石龙路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙漕路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '漕溪路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宜山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '延安西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中山公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金沙江路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '曹杨路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '镇坪路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中潭路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宝山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东宝兴路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹口足球场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '赤峰路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大柏树', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江湾镇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '殷高西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '长江南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '淞发路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '张华浜', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '淞滨路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '水产路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宝杨路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '友谊路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '铁力路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江杨北路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_4 = [
    ['name' => '虹桥路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '延安西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中山公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金沙江路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '曹杨路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '镇坪路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中潭路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海火车站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宝山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '海伦路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '临平路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大连路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '杨树浦路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '浦东大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '世纪大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '浦电路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '蓝村路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '塘桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '南浦大桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '西藏南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '鲁班路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大木桥路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东安路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海体育场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海体育馆', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宜山路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_5 = [
    ['name' => '莘庄', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '春申路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '银都路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '颛桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '北桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '剑川路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东川路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金平路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '华宁路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '文井路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '闵行开发区', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_6 = [
    ['name' => '港城路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '外高桥保税区北', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '航津路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '外高桥保税区南', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '洲海路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '五洲大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东靖路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '巨峰路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '五莲路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '博兴路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金桥路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '云山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '德平路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '北洋泾路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '民生路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '源深体育中心', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '世纪大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '浦电路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '蓝村路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海儿童医学中心', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '临沂新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '高科西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东明路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '高青路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '华夏西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '灵岩南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东方体育中心', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_7 = [
    ['name' => '美兰湖', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '罗南新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '潘广路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '刘行', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '顾村公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海大学', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '南陈路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上大路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '场中路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大场镇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '行知路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大华三路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '新村路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '岚皋路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '镇坪路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '长寿路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '昌平路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '静安寺', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '常熟路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '肇嘉浜路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东安路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '船厂路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '后滩', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '长清路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '耀华路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '云台路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '高科西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '杨高南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '锦绣路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '芳华路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙阳路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '花木路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_8 = [
    ['name' => '市光路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '嫩江路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '翔殷路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '黄兴公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '延吉中路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '黄兴路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江浦路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '鞍山新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '四平路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '曲阳路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹口足球场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '西藏北路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中兴路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '曲阜路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '人民广场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大世界', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '老西门', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '陆家浜路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '西藏南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中华艺术宫', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '耀华路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '成山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '杨思', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东方体育中心', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '凌兆新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '芦恒路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '浦江镇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江月路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '联航路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '沈社公路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_9 = [
    ['name' => '杨高中路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '世纪大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '商城路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '小南门', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '陆家浜路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '马当路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '打浦桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '嘉善路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '肇嘉浜路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '徐家汇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宜山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '桂林路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '漕河泾开发区', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '合川路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '星中路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '七宝', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '中春路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '九亭', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '泗泾', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '佘山', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '洞泾', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '松江大学城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '松江新城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '松江南', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_10 = [
    ['name' => '新江湾城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '殷高东路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '三门路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江湾体育场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '五角场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '国权路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '同济大学', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '四平路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '邮电新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '海伦路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '四川北路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '天潼路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '南京东路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '豫园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '老西门', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '新天地', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '陕西南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海图书馆', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '交通大学', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宋园路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '伊犁路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '水城路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙溪路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海动物园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥1号航站楼', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥2号航站楼', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '虹桥火车站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙柏新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '紫藤路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '航中路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_11 = [
    ['name' => '罗山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '御桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '浦三路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '三林东', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '三林', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东方体育中心', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙耀路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '云锦路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '龙华', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海游泳馆', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '徐家汇', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '交通大学', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江苏路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '隆德路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '曹杨路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '枫桥路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '真如', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海西站', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '李子园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '祁连山路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '武威路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '桃浦新村', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '南翔', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '马陆', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '嘉定新城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '白银路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '嘉定西', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '嘉定北', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海赛车场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '昌吉东路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '上海汽车城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '安亭', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '兆丰路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '光明路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '花桥', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_12 = [
    ['name' => '天潼路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '国际客运中心', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '提篮桥', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '大连路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '江浦公园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '宁国路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '隆昌路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '爱国路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '复兴岛', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '东陆路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '巨峰路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '杨高北路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金京路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '申江路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金海路', 'code' => 1, 'lat' => 1, 'long' => 1],
];

$line_13 = [
    ['name' => '金运路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金沙江西路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '丰庄', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '祁连山南路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '真北路', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '金沙江路', 'code' => 1, 'lat' => 1, 'long' => 1],
];


$line_16 = [
    ['name' => '滴水湖', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '临港大道', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '书院', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '惠南东', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '惠南', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '野生动物园', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '新场', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '航头东', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '鹤沙航城', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '周浦东', 'code' => 1, 'lat' => 1, 'long' => 1],
    ['name' => '罗山路', 'code' => 1, 'lat' => 1, 'long' => 1],
];
